# Состояния разговоров
SELECTING_ACTION = 0

# Wildberries
WB_REPORT_FILES = 1
WB_REMAINS_FILES = 2
WB_REMAINS_CABINET_CHOICE=3
WB_REPORT_CABINET_CHOICE=11

# Ozon — остатки
OZON_REMAINS_CABINET_CHOICE = 4

# Штрихкоды и CSV
BARCODE_FILES = 5
CSV_FILES = 6

# Ozon — продажи (новое)
OZON_SALES_CABINET_CHOICE = 7
OZON_SALES_DATE_START = 8
OZON_SALES_DATE_END = 9

ALL_MP_REMAINS = 10