# Состояния разговоров
(
    SELECTING_ACTION,
    WB_REPORT_FILES,
    OZON_REMAINS_CABINET_CHOICE,
    OZON_REMAINS_REPORT_TYPE,
    OZON_SALES_CABINET_CHOICE,
    OZON_SALES_DATE_INPUT,
    WB_REMAINS_FILES,
    BARCODE_FILES,
    CSV_FILES
) = range(9)